-- ==============================================================================
-- EXAM PREPARATION PLANNER SCHEMA
-- Reverse Countdown: syllabus topics, daily targets, past paper scheduler
-- ==============================================================================

-- Syllabus topics per subject (from your syllabus PDFs)
CREATE TABLE syllabus_topics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  subject_code TEXT NOT NULL,
  topic_code TEXT NOT NULL,               -- e.g., "EC201-U1", "MA201-Laplace"
  topic_name TEXT NOT NULL,               -- "PN Junction Diode", "Laplace Transform"
  unit_number INTEGER,                    -- syllabus unit/chapter number
  order_in_subject INTEGER NOT NULL,      -- study order
  estimated_hours DECIMAL(4,1) DEFAULT 2.0, -- estimated study time
  difficulty INTEGER DEFAULT 3 CHECK (difficulty BETWEEN 1 AND 5), -- 1=easy, 5=hard
  weightage_estimate DECIMAL(5,2),        -- estimated exam weightage %
  is_core BOOLEAN DEFAULT TRUE,           -- core vs optional
  prerequisites TEXT[],                   -- array of topic_codes that should be done first
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  UNIQUE(user_id, subject_code, topic_code)
);

-- Syllabus coverage tracking
CREATE TABLE topic_coverage (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  topic_id UUID NOT NULL REFERENCES syllabus_topics(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'NOT_STARTED' 
    CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'COVERED', 'REVISING', 'MASTERED')),
  confidence INTEGER DEFAULT 0 CHECK (confidence BETWEEN 0 AND 100), -- self-assessed mastery
  hours_spent DECIMAL(4,1) DEFAULT 0,
  last_studied DATE,
  last_revised DATE,
  next_review DATE,                       -- spaced repetition
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  UNIQUE(user_id, topic_id)
);

-- Exam schedule (midsem, endsem, quizzes)
CREATE TABLE exam_schedule (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  subject_code TEXT NOT NULL,
  exam_type TEXT NOT NULL 
    CHECK (exam_type IN ('MIDSEM', 'ENDSEM', 'QUIZ', 'LAB_EXAM', 'VIVA', 'ASSIGNMENT_DUE')),
  exam_name TEXT NOT NULL,                -- "Midsem", "Endsem", "Quiz 1"
  exam_date DATE NOT NULL,
  start_time TIME,
  end_time TIME,
  venue TEXT,
  syllabus_coverage TEXT[],               -- array of topic_codes covered
  max_marks INTEGER,
  weightage DECIMAL(5,2),                 -- weight in final grade
  is_confirmed BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Past paper database
CREATE TABLE past_papers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  subject_code TEXT NOT NULL,
  year INTEGER NOT NULL,
  exam_type TEXT NOT NULL 
    CHECK (exam_type IN ('MIDSEM', 'ENDSEM', 'QUIZ')),
  semester TEXT,                          -- "Odd 2024-25", "Even 2023-24"
  file_path TEXT,                         -- local/path or supabase storage
  file_name TEXT,
  has_solutions BOOLEAN DEFAULT FALSE,
  solution_file_path TEXT,
  topics_covered TEXT[],                  -- array of topic_codes
  difficulty_rating INTEGER CHECK (difficulty_rating BETWEEN 1 AND 5),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Past paper practice log
CREATE TABLE paper_practice (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  paper_id UUID NOT NULL REFERENCES past_papers(id) ON DELETE CASCADE,
  attempted_date DATE NOT NULL DEFAULT CURRENT_DATE,
  score_obtained DECIMAL(5,2),
  max_score DECIMAL(5,2),
  time_taken_minutes INTEGER,
  questions_attempted INTEGER,
  total_questions INTEGER,
  weak_topics TEXT[],                     -- topic_codes where mistakes made
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Daily study plan (generated by reverse countdown algorithm)
CREATE TABLE daily_study_plan (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  plan_date DATE NOT NULL,
  subject_code TEXT NOT NULL,
  topic_id UUID REFERENCES syllabus_topics(id) ON DELETE SET NULL,
  planned_hours DECIMAL(3,1) NOT NULL,
  actual_hours DECIMAL(3,1) DEFAULT 0,
  session_type TEXT NOT NULL 
    CHECK (session_type IN ('NEW_TOPIC', 'REVISION', 'PRACTICE', 'MOCK_TEST', 'DOUBT_CLEARING')),
  priority INTEGER DEFAULT 2 CHECK (priority BETWEEN 1 AND 3), -- 1=high, 2=med, 3=low
  status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', 'RESCHEDULED')),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  UNIQUE(user_id, plan_date, subject_code, topic_id, session_type)
);

-- Study session log (actual sessions done)
CREATE TABLE study_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_date DATE NOT NULL DEFAULT CURRENT_DATE,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ,
  subject_code TEXT NOT NULL,
  topic_id UUID REFERENCES syllabus_topics(id) ON DELETE SET NULL,
  session_type TEXT NOT NULL 
    CHECK (session_type IN ('NEW_TOPIC', 'REVISION', 'PRACTICE', 'MOCK_TEST', 'DOUBT_CLEARING')),
  planned_duration_minutes INTEGER,
  actual_duration_minutes INTEGER,
  focus_rating INTEGER CHECK (focus_rating BETWEEN 1 AND 5),
  coverage_status TEXT CHECK (coverage_status IN ('NOT_STARTED', 'IN_PROGRESS', 'COVERED', 'REVISING', 'MASTERED')),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Reverse countdown configuration
CREATE TABLE planner_config (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  subject_code TEXT NOT NULL UNIQUE,
  target_exam_date DATE NOT NULL,         -- usually endsem date
  buffer_days INTEGER DEFAULT 7,          -- days before exam to stop new topics
  revision_cycles INTEGER DEFAULT 3,      -- number of full revision passes
  daily_study_hours DECIMAL(3,1) DEFAULT 4.0,
  preferred_session_length_minutes INTEGER DEFAULT 90,
  break_between_sessions_minutes INTEGER DEFAULT 15,
  weak_topic_extra_time_multiplier DECIMAL(3,2) DEFAULT 1.5,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX idx_syllabus_user_subject ON syllabus_topics(user_id, subject_code);
CREATE INDEX idx_coverage_user_topic ON topic_coverage(user_id, topic_id);
CREATE INDEX idx_exam_schedule_user_date ON exam_schedule(user_id, exam_date);
CREATE INDEX idx_past_papers_user_subject ON past_papers(user_id, subject_code);
CREATE INDEX idx_practice_user_paper ON paper_practice(user_id, paper_id);
CREATE INDEX idx_daily_plan_user_date ON daily_study_plan(user_id, plan_date);
CREATE INDEX idx_study_sessions_user_date ON study_sessions(user_id, session_date);

-- RLS
ALTER TABLE syllabus_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE topic_coverage ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE past_papers ENABLE ROW LEVEL SECURITY;
ALTER TABLE paper_practice ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_study_plan ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner_config ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users manage their own syllabus" ON syllabus_topics
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage their own coverage" ON topic_coverage
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage their own exams" ON exam_schedule
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage their own past papers" ON past_papers
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage their own practice" ON paper_practice
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage their own daily plan" ON daily_study_plan
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage their own sessions" ON study_sessions
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage their own planner config" ON planner_config
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Grants
GRANT SELECT, INSERT, UPDATE, DELETE ON syllabus_topics TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON topic_coverage TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON exam_schedule TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON past_papers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON paper_practice TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON daily_study_plan TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON study_sessions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON planner_config TO authenticated;

-- Triggers
CREATE TRIGGER update_syllabus_updated_at BEFORE UPDATE ON syllabus_topics
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TRIGGER update_coverage_updated_at BEFORE UPDATE ON topic_coverage
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TRIGGER update_exam_schedule_updated_at BEFORE UPDATE ON exam_schedule
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TRIGGER update_daily_plan_updated_at BEFORE UPDATE ON daily_study_plan
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TRIGGER update_planner_config_updated_at BEFORE UPDATE ON planner_config
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();